[features]
seeds = false
skip-lint = false
[programs.devnet]
token_presale = "9XVrUktfDzVjFLqU3dMNdmPkNon3BAdpURiAYLcVEnGe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "./deployer_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
