import type { Metadata } from "next";
import "./globals.css";
import Header from "@/layouts/header";
import { jollyFont, interFont, fingerFont } from "./fonts";
import cx from "classnames";
import WalletContextProvider from "@/providers/WalletContextProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cx(
      jollyFont.variable,
      fingerFont.variable,
      interFont.variable
    )}>
      <body className={`font-inter `}>
        <WalletContextProvider >
          <main className="flex flex-col items-center relative bg-landing bg-no-repeat	bg-cover bg-center px-16 py-12 h-full desktop_sm:h-full ">
            <Header />
            {children}
          </main>
          <ToastContainer autoClose={3000} draggableDirection="x" />
        </WalletContextProvider>
      </body>
    </html>
  );
}
