import type { Metadata } from "next";
import "./globals.css";
import Header from "@/layouts/header";
import { jollyFont, interFont, fingerFont } from "./fonts";
import cx from "classnames";
import WalletContextProvider from "@/providers/WalletContextProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cx(
      jollyFont.variable,
      fingerFont.variable,
      interFont.variable
    )}>
      <body className={`font-inter `}>
        <WalletContextProvider >
          <main className="flex flex-col items-center bg-no-repeat	bg-cover bg-center px-16  h-full desktop_sm:h-full relative ">
            <div className="w-full absolute h-full">
              <video autoPlay playsInline muted loop className="absolute -z-9">
                <source src="//videos.ctfassets.net/beeay9aupl8z/2nonazyKM6beq7FI4MhJfO/926ad2c9a58e02ac746b26e405fc610c/seagulls.mp4" />
              </video>
            </div>
            <Header />
            {children}
          </main>
          <ToastContainer autoClose={3000} draggableDirection="x" />
        </WalletContextProvider>
      </body>
    </html>
  );
}
